Repository AY2021S2-CS2103T-W10-3/tp, pull requests merged in 2021-03, with the labels that each got.

#20 Update done command
  docs/DeveloperGuide.md
  docs/index.md
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DoneCommandParser.java
  src/main/java/seedu/address/model/person/Done.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/DoneCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story

#27 Update message
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/person/Name.java
Labels: enhancement

#35 Update Find Command to get Address
  src/main/java/seedu/address/model/person/Date.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/model/person/DateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: type.tasks

#47 Add date field and enable searching by date
  src/main/java/seedu/timeforwheels/logic/commands/AddCommand.java
  src/main/java/seedu/timeforwheels/logic/commands/DoneCommand.java
  src/main/java/seedu/timeforwheels/logic/commands/EditCommand.java
  src/main/java/seedu/timeforwheels/logic/commands/RemarkCommand.java
  src/main/java/seedu/timeforwheels/logic/parser/AddCommandParser.java
  src/main/java/seedu/timeforwheels/logic/parser/CliSyntax.java
  src/main/java/seedu/timeforwheels/logic/parser/EditCommandParser.java
  src/main/java/seedu/timeforwheels/logic/parser/ParserUtil.java
  src/main/java/seedu/timeforwheels/model/customer/Customer.java
  src/main/java/seedu/timeforwheels/model/customer/NameContainsKeywordsPredicate.java
  src/main/java/seedu/timeforwheels/model/util/SampleDataUtil.java
  src/main/java/seedu/timeforwheels/storage/JsonAdaptedCustomer.java
  src/main/java/seedu/timeforwheels/ui/CustomerCard.java
  src/main/resources/view/CustomerListCard.fxml
  src/test/data/JsonSerializableDeliveryListTest/duplicateCustomerDeliveryList.json
  src/test/data/JsonSerializableDeliveryListTest/typicalCustomersDeliveryList.json
  src/test/java/seedu/timeforwheels/logic/LogicManagerTest.java
  src/test/java/seedu/timeforwheels/logic/commands/CommandTestUtil.java
  src/test/java/seedu/timeforwheels/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/timeforwheels/storage/JsonAdaptedCustomerTest.java
  src/test/java/seedu/timeforwheels/testutil/CustomerBuilder.java
  src/test/java/seedu/timeforwheels/testutil/CustomerUtil.java
Labels: type.tasks

#48 Add assertion
  src/main/java/seedu/timeforwheels/model/customer/Date.java
  src/main/java/seedu/timeforwheels/ui/CustomerCard.java
Labels: enhancement

#52 Update stats command
  src/main/java/seedu/timeforwheels/logic/commands/StatsCommand.java
  src/main/java/seedu/timeforwheels/logic/parser/DeliveryListParser.java
  src/main/java/seedu/timeforwheels/model/customer/Customer.java
  src/main/java/seedu/timeforwheels/model/customer/Date.java
  src/main/java/seedu/timeforwheels/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableDeliveryListTest/duplicateCustomerDeliveryList.json
  src/test/data/JsonSerializableDeliveryListTest/typicalCustomersDeliveryList.json
  src/test/java/seedu/timeforwheels/logic/commands/CommandTestUtil.java
  src/test/java/seedu/timeforwheels/logic/commands/StatsCommandTest.java
  src/test/java/seedu/timeforwheels/storage/JsonSerializableDeliveryListTest.java
  src/test/java/seedu/timeforwheels/testutil/TypicalCustomers.java
Labels: type.Story

#56 Fix title of developer guide
  docs/DeveloperGuide.md
  docs/team/juhaer.md
Labels: documentation

#58 Update User Guide to add find command
  docs/UserGuide.md
  docs/images/FindAddress.png
  docs/images/FindDate.png
  docs/images/FindName.png
  docs/images/FindTelephone.png
  docs/team/juhaer.md
Labels: documentation

#63 Include other parameters in find method
  docs/team/juhaer.md
  src/main/java/seedu/timeforwheels/model/customer/NameContainsKeywordsPredicate.java
  src/test/java/seedu/timeforwheels/model/customer/NameContainsKeywordsPredicateTest.java
Labels: enhancement
